services:
  etf-collector:
    image: ghcr.io/artiveloper/etfview-collector:latest
    build: .
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/logs
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    user: "1001:1001"
    restart: unless-stopped
